// in layout you just set the priciple that we follow throughout the app.

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConvexClerkProvider from "@/components/providers/ConvexClerkProvider";

import Navbar from "@/components/Navbar";
import { RedirectToSignIn, SignedIn, SignedOut } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";

/*
  MetaData -> type for the metaData object used by Next.js (page title, description)
  Geist, Geist_Mono -> google fonts imported via Next.js font opimization
  ./global.css -> Global Css for the app
  ConvexClerkProvider -> Custom provider to wrap convex dataase and clerk auth context for the whole app
  Navbar -> navigation component.
  SignedIn, SignedOut, RedirectToSignIn -> Components from clerk for authentication handling
  Toaster -> React hot toast notifications
*/

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/*
  Loads Google fonts Geist(sans) and Geist Mono(monospace)
  Uses Css Variables -- font-geist-sans and --font-geist-mono so you can apply them in your CSS
*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// sets page title and description for SEO and social previews

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexClerkProvider>

      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* ✅ Navbar visible to everyone */}
          <Navbar />

          {/* ✅ Show content only if signed in, otherwise redirect */}
          <SignedIn>{children}</SignedIn>
          <SignedOut>
            <RedirectToSignIn />
          </SignedOut>
          <Toaster/>
        </body>
      </html>
    </ConvexClerkProvider>
  );
}

/*
  1. ConvexClerkProvider
      wraps the entire app.
      Provides Convex DB context and clerk authentication context to all child components.
  2. <html lang="en">
      sets the document language
  3. <body>
      applies fonts via class names
      antialiased -> smoothens font rendering
  4.<Navbar/>
      always visible , even if user is not signed in.
  5. <SignedIn>
      Renders children only if the user is authenticated
  6.  <SignedOut>
      Redirects user to the sign0in page if they are not logged in.
  7 <Toaster/>
      Enables toast notification anywhere in the app.
*/
